name: codec_eval
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - pkgs/main/linux-64::_libgcc_mutex==0.1=main
  - pkgs/main/linux-64::blas==1.0=mkl
  - conda-forge/noarch::ca-certificates==2025.8.3=hbd8a1cb_0
  - nvidia/linux-64::cuda-cudart==12.4.127=0
  - nvidia/linux-64::cuda-cupti==12.4.127=0
  - nvidia/linux-64::cuda-nvrtc==12.4.127=0
  - nvidia/linux-64::cuda-nvtx==12.4.127=0
  - nvidia/noarch::cuda-version==12.8=3
  - pkgs/main/linux-64::ld_impl_linux-64==2.40=h12ee557_0
  - nvidia/linux-64::libcublas==12.4.5.8=0
  - nvidia/linux-64::libcufft==11.2.1.3=0
  - nvidia/linux-64::libcusolver==11.6.1.9=0
  - nvidia/linux-64::libcusparse==12.3.1.170=0
  - nvidia/linux-64::libnpp==12.2.5.30=0
  - nvidia/linux-64::libnvjitlink==12.4.127=0
  - nvidia/linux-64::libnvjpeg==12.3.1.117=0
  - pkgs/main/linux-64::libstdcxx-ng==11.2.0=h1234567_1
  - pytorch/noarch::pytorch-mutex==1.0=cuda
  - pkgs/main/noarch::tzdata==2025a=h04d1e81_0
  - pkgs/main/linux-64::libgomp==11.2.0=h1234567_1
  - pkgs/main/linux-64::_openmp_mutex==5.1=1_gnu
  - pkgs/main/linux-64::libgcc-ng==11.2.0=h1234567_1
  - pkgs/main/linux-64::aws-c-common==0.8.5=h5eee18b_0
  - pkgs/main/linux-64::bzip2==1.0.8=h5eee18b_6
  - pkgs/main/linux-64::c-ares==1.19.1=h5eee18b_0
  - pkgs/main/linux-64::gflags==2.2.2=h6a678d5_1
  - pkgs/main/linux-64::giflib==5.2.2=h5eee18b_0
  - pkgs/main/linux-64::gmp==6.3.0=h6a678d5_0
  - pkgs/main/linux-64::icu==73.1=h6a678d5_0
  - pkgs/main/linux-64::jpeg==9e=h5eee18b_3
  - pkgs/main/linux-64::lame==3.100=h7b6447c_0
  - pkgs/main/linux-64::lerc==4.0.0=h6a678d5_0
  - pkgs/main/linux-64::libabseil==20250127.0=cxx17_h6a678d5_0
  - pkgs/main/linux-64::libbrotlicommon==1.0.9=h5eee18b_9
  - nvidia/linux-64::libcufile==1.13.1.3=0
  - nvidia/linux-64::libcurand==10.3.9.90=0
  - pkgs/main/linux-64::libdeflate==1.22=h5eee18b_0
  - pkgs/main/linux-64::libev==4.33=h7f8727e_1
  - pkgs/main/linux-64::libffi==3.4.4=h6a678d5_1
  - pkgs/main/linux-64::libiconv==1.16=h5eee18b_3
  - pytorch/linux-64::libjpeg-turbo==2.0.0=h9bf148f_0
  - nvidia/linux-64::libnvfatbin==12.8.90=0
  - conda-forge/linux-64::libsodium==1.0.18=h36c2ea0_1
  - pkgs/main/linux-64::libtasn1==4.19.0=h5eee18b_0
  - pkgs/main/linux-64::libunistring==0.9.10=h27cfd23_0
  - pkgs/main/linux-64::libuuid==1.41.5=h5eee18b_0
  - pkgs/main/linux-64::libwebp-base==1.3.2=h5eee18b_1
  - pkgs/main/linux-64::lz4-c==1.9.4=h6a678d5_1
  - pkgs/main/linux-64::ncurses==6.4=h6a678d5_0
  - pkgs/main/linux-64::ocl-icd==2.3.2=h5eee18b_1
  - pkgs/main/linux-64::openh264==2.1.1=h4ff587b_0
  - pkgs/main/linux-64::openssl==3.0.17=h5eee18b_0
  - pkgs/main/linux-64::snappy==1.2.1=h6a678d5_0
  - pkgs/main/linux-64::tbb==2021.8.0=hdb19cb5_0
  - pkgs/main/linux-64::utf8proc==2.6.1=h5eee18b_1
  - pkgs/main/linux-64::xxhash==0.8.0=h7f8727e_3
  - pkgs/main/linux-64::xz==5.6.4=h5eee18b_1
  - pkgs/main/linux-64::yaml==0.2.5=h7b6447c_0
  - pkgs/main/linux-64::zlib==1.2.13=h5eee18b_1
  - pkgs/main/linux-64::aws-c-cal==0.5.20=hdbd6064_0
  - pkgs/main/linux-64::aws-c-compression==0.2.16=h5eee18b_0
  - pkgs/main/linux-64::aws-c-sdkutils==0.1.6=h5eee18b_0
  - pkgs/main/linux-64::aws-checksums==0.1.13=h5eee18b_0
  - nvidia/linux-64::cuda-opencl==12.8.90=0
  - pkgs/main/linux-64::glog==0.5.0=h6a678d5_1
  - pkgs/main/linux-64::intel-openmp==2023.1.0=hdb19cb5_46306
  - pkgs/main/linux-64::libbrotlidec==1.0.9=h5eee18b_9
  - pkgs/main/linux-64::libbrotlienc==1.0.9=h5eee18b_9
  - pkgs/main/linux-64::libedit==3.1.20230828=h5eee18b_0
  - pkgs/main/linux-64::libevent==2.1.12=hdbd6064_1
  - pkgs/main/linux-64::libidn2==2.3.4=h5eee18b_0
  - pkgs/main/linux-64::libnghttp2==1.57.0=h2d74bed_0
  - pkgs/main/linux-64::libpng==1.6.39=h5eee18b_0
  - pkgs/main/linux-64::libprotobuf==5.29.3=hc99497a_0
  - pkgs/main/linux-64::libre2-11==2024.07.02=h6a678d5_0
  - pkgs/main/linux-64::libssh2==1.11.1=h251f7ec_0
  - pkgs/main/linux-64::llvm-openmp==14.0.6=h9e868ea_0
  - pkgs/main/linux-64::mpfr==4.2.1=h5eee18b_0
  - pkgs/main/linux-64::nettle==3.7.3=hbbd107a_1
  - pkgs/main/linux-64::readline==8.2=h5eee18b_0
  - pkgs/main/linux-64::s2n==1.3.27=hdbd6064_0
  - pkgs/main/linux-64::tk==8.6.14=h39e8969_0
  - pkgs/main/linux-64::zeromq==4.3.5=h6a678d5_0
  - pkgs/main/linux-64::zstd==1.5.6=hc292b87_0
  - pkgs/main/linux-64::aws-c-io==0.13.10=h5eee18b_0
  - nvidia/linux-64::cuda-libraries==12.4.1=0
  - pkgs/main/linux-64::freetype==2.12.1=h4a9f257_0
  - pkgs/main/linux-64::gnutls==3.6.15=he1e5248_0
  - pkgs/main/linux-64::krb5==1.20.1=h143b758_1
  - pkgs/main/linux-64::libboost==1.82.0=h109eef0_2
  - pkgs/main/linux-64::libtiff==4.5.1=hffd6297_1
  - pkgs/main/linux-64::mkl==2023.1.0=h213fc3f_46344
  - pkgs/main/linux-64::mpc==1.3.1=h5eee18b_0
  - pkgs/main/linux-64::orc==2.1.1=hd396ef6_0
  - pkgs/main/linux-64::re2==2024.07.02=hdb19cb5_0
  - pkgs/main/linux-64::sqlite==3.45.3=h5eee18b_0
  - pkgs/main/linux-64::aws-c-event-stream==0.2.15=h6a678d5_0
  - pkgs/main/linux-64::aws-c-http==0.6.25=h5eee18b_0
  - pkgs/main/linux-64::boost-cpp==1.82.0=hdb19cb5_2
  - nvidia/linux-64::cuda-runtime==12.4.1=0
  - pytorch/linux-64::ffmpeg==4.3=hf484d3e_0
  - pkgs/main/linux-64::lcms2==2.16=hb9589c4_0
  - pkgs/main/linux-64::libcurl==8.12.1=hc9e6f67_0
  - pkgs/main/linux-64::libgrpc==1.71.0=h2d74bed_0
  - pkgs/main/linux-64::libwebp==1.3.2=h11a3e52_0
  - pkgs/main/linux-64::openjpeg==2.5.2=he7f1fd0_0
  - pkgs/main/linux-64::python==3.10.16=he870216_1
  - pkgs/main/linux-64::aiohappyeyeballs==2.4.4=py310h06a4308_0
  - conda-forge/noarch::asttokens==3.0.0=pyhd8ed1ab_1
  - pkgs/main/linux-64::async-timeout==5.0.1=py310h06a4308_0
  - pkgs/main/linux-64::attrs==24.3.0=py310h06a4308_0
  - pkgs/main/linux-64::aws-c-auth==0.6.19=h5eee18b_0
  - pkgs/main/linux-64::aws-c-mqtt==0.7.13=h5eee18b_0
  - pkgs/main/linux-64::brotli-python==1.0.9=py310h6a678d5_9
  - conda-forge/noarch::certifi==2025.8.3=pyhd8ed1ab_0
  - pkgs/main/noarch::charset-normalizer==3.3.2=pyhd3eb1b0_0
  - pkgs/main/linux-64::debugpy==1.8.11=py310h6a678d5_0
  - conda-forge/noarch::decorator==5.2.1=pyhd8ed1ab_0
  - pkgs/main/linux-64::dill==0.3.8=py310h06a4308_0
  - conda-forge/noarch::entrypoints==0.4=pyhd8ed1ab_1
  - conda-forge/noarch::executing==2.2.0=pyhd8ed1ab_0
  - pkgs/main/linux-64::filelock==3.13.1=py310h06a4308_0
  - pkgs/main/linux-64::frozenlist==1.5.0=py310h5eee18b_0
  - pkgs/main/linux-64::fsspec==2024.12.0=py310h06a4308_0
  - pkgs/main/linux-64::gmpy2==2.2.1=py310h5eee18b_0
  - pkgs/main/linux-64::idna==3.7=py310h06a4308_0
  - pkgs/main/linux-64::libthrift==0.15.0=h1795dd8_2
  - pkgs/main/linux-64::markupsafe==3.0.2=py310h5eee18b_0
  - pkgs/main/linux-64::mkl-service==2.4.0=py310h5eee18b_2
  - pkgs/main/linux-64::mpmath==1.3.0=py310h06a4308_0
  - conda-forge/noarch::nest-asyncio==1.6.0=pyhd8ed1ab_1
  - pkgs/main/linux-64::networkx==3.4.2=py310h06a4308_0
  - pkgs/main/linux-64::packaging==24.2=py310h06a4308_0
  - conda-forge/noarch::parso==0.8.4=pyhd8ed1ab_1
  - conda-forge/noarch::pickleshare==0.7.5=pyhd8ed1ab_1004
  - pkgs/main/linux-64::pillow==11.1.0=py310hcea889d_0
  - conda-forge/noarch::platformdirs==4.3.8=pyhe01879c_0
  - pkgs/main/linux-64::propcache==0.3.1=py310h5eee18b_0
  - pkgs/main/linux-64::protobuf==5.29.3=py310he621ea3_0
  - pkgs/main/linux-64::psutil==5.9.0=py310h5eee18b_1
  - conda-forge/noarch::ptyprocess==0.7.0=pyhd8ed1ab_1
  - conda-forge/noarch::pure_eval==0.2.3=pyhd8ed1ab_1
  - conda-forge/noarch::pygments==2.19.1=pyhd8ed1ab_0
  - pkgs/main/linux-64::pysocks==1.7.1=py310h06a4308_0
  - pkgs/main/noarch::python-tzdata==2023.3=pyhd3eb1b0_0
  - pkgs/main/linux-64::python-xxhash==3.5.0=py310h5eee18b_0
  - conda-forge/linux-64::python_abi==3.10=2_cp310
  - pytorch/linux-64::pytorch-cuda==12.4=hc786d27_7
  - pkgs/main/linux-64::pytz==2024.1=py310h06a4308_0
  - pkgs/main/linux-64::pyyaml==6.0.2=py310h5eee18b_0
  - pkgs/main/linux-64::pyzmq==26.2.0=py310h6a678d5_0
  - pkgs/main/linux-64::regex==2024.11.6=py310h5eee18b_0
  - pkgs/main/linux-64::safetensors==0.5.3=py310h922eef2_0
  - pkgs/main/linux-64::setuptools==75.8.0=py310h06a4308_0
  - pkgs/main/linux-64::six==1.17.0=py310h06a4308_0
  - pkgs/main/linux-64::tqdm==4.67.1=py310h2f386ee_0
  - conda-forge/noarch::traitlets==5.14.3=pyhd8ed1ab_1
  - pkgs/main/linux-64::typing_extensions==4.12.2=py310h06a4308_0
  - conda-forge/noarch::wcwidth==0.2.13=pyhd8ed1ab_1
  - pkgs/main/linux-64::wheel==0.45.1=py310h06a4308_0
  - pkgs/main/noarch::aiosignal==1.2.0=pyhd3eb1b0_0
  - pkgs/main/linux-64::aws-c-s3==0.1.51=hdbd6064_0
  - conda-forge/noarch::comm==0.2.2=pyhd8ed1ab_1
  - conda-forge/noarch::conda-pack==0.8.1=pyhd8ed1ab_1
  - conda-forge/noarch::exceptiongroup==1.3.0=pyhd8ed1ab_0
  - conda-forge/noarch::jedi==0.19.2=pyhd8ed1ab_1
  - pkgs/main/linux-64::jinja2==3.1.6=py310h06a4308_0
  - conda-forge/noarch::jupyter_core==5.7.2=pyh31011fe_1
  - conda-forge/noarch::matplotlib-inline==0.1.7=pyhd8ed1ab_1
  - pkgs/main/linux-64::multiprocess==0.70.15=py310h06a4308_0
  - pkgs/main/linux-64::numpy-base==2.0.1=py310hb5e798b_1
  - conda-forge/noarch::pexpect==4.9.0=pyhd8ed1ab_1
  - pkgs/main/linux-64::pip==25.0=py310h06a4308_0
  - conda-forge/noarch::prompt-toolkit==3.0.51=pyha770c72_0
  - pkgs/main/linux-64::python-dateutil==2.9.0post0=py310h06a4308_2
  - conda-forge/noarch::stack_data==0.6.3=pyhd8ed1ab_1
  - pkgs/main/linux-64::sympy==1.13.3=py310h06a4308_1
  - conda-forge/linux-64::tornado==6.1=py310h5764c6d_3
  - pkgs/main/linux-64::typing-extensions==4.12.2=py310h06a4308_0
  - pkgs/main/linux-64::urllib3==2.3.0=py310h06a4308_0
  - pkgs/main/linux-64::aws-crt-cpp==0.18.16=h6a678d5_0
  - conda-forge/noarch::ipython==8.36.0=pyh907856f_0
  - conda-forge/noarch::jupyter_client==7.3.4=pyhd8ed1ab_0
  - pkgs/main/linux-64::multidict==6.1.0=py310h5eee18b_0
  - pkgs/main/linux-64::requests==2.32.3=py310h06a4308_1
  - pkgs/main/linux-64::aws-sdk-cpp==1.11.212=hecad206_0
  - pkgs/main/linux-64::huggingface_hub==0.29.2=py310h06a4308_0
  - conda-forge/noarch::ipykernel==6.29.5=pyh3099207_0
  - pkgs/main/linux-64::yarl==1.18.0=py310h5eee18b_0
  - pkgs/main/linux-64::aiohttp==3.11.10=py310h5eee18b_0
  - pkgs/main/linux-64::arrow-cpp==19.0.0=h865e1df_2
  - pkgs/main/linux-64::tokenizers==0.21.0=py310ha92566c_0
  - pkgs/main/linux-64::bottleneck==1.4.2=py310ha9d4c09_0
  - pkgs/main/linux-64::mkl_fft==1.3.11=py310h5eee18b_0
  - pkgs/main/linux-64::mkl_random==1.2.8=py310h1128e8f_0
  - pkgs/main/linux-64::numpy==2.0.1=py310h5f9d8c6_1
  - pkgs/main/linux-64::numexpr==2.10.1=py310h3c60e43_0
  - pkgs/main/linux-64::pyarrow==19.0.0=py310h6a678d5_1
  - pkgs/main/linux-64::pandas==2.2.3=py310h6a678d5_0
  - pkgs/main/linux-64::datasets==3.3.2=py310h06a4308_0
  - pkgs/main/linux-64::transformers==4.49.0=py310h06a4308_0
  - pytorch/linux-64::pytorch==2.5.0=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch/linux-64::torchaudio==2.5.0=py310_cu124
  - pytorch/linux-64::torchtriton==3.1.0=py310
  - pytorch/linux-64::torchvision==0.20.0=py310_cu124
prefix: /mnt/nas1/anaconda3/envs/codec_eval
