name: codec
channels:
  - pytorch
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.3.0=h27087fc_1
  - binutils_impl_linux-64=2.40=h5293946_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=5.0.1=h964e5f1_2
  - filelock=3.20.0=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - gcc=9.5.0=h1fea6ba_13
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312hcaba1f9_2
  - gnutls=3.6.13=h85f3911_1
  - gxx=9.5.0=h1fea6ba_13
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - icu=70.1=h27087fc_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.8.0=hca28451_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=he0feb66_14
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=15.2.0=h69a702a_14
  - libgl=1.7.0=ha4b6fd6_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_14
  - libiconv=1.18=h3b78370_2
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.43=h2797004_0
  - libsanitizer=9.5.0=h2f262e1_19
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nettle=3.6=he412f7d_0
  - ninja=1.13.2=h171cf75_0
  - numpy-base=2.0.1=py312h0da6c21_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openh264=2.1.1=h780b84a_0
  - openssl=3.6.0=h26f9b46_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.11=h22baa00_0
  - python_abi=3.12=2_cp312
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.3=py312h8a5da7c_0
  - readline=8.3=hc2a1206_0
  - rhash=1.4.6=hb9d3cd8_1
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=1.1.0=h27087fc_1
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.5.0=h924138e_1
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=py312_cu124
  - torchtriton=3.1.0=py312
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wayland=1.24.0=hdac8c69_0
  - wayland-protocols=1.46=hd8ed1ab_0
  - wheel=0.45.1=py312h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - anyio==4.11.0
      - argbind==0.3.9
      - asttokens==3.0.0
      - attrs==25.4.0
      - audioread==3.1.0
      - beautifulsoup4==4.14.2
      - bitarray==3.8.0
      - brotli==1.2.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cmake==4.2.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.1
      - decorator==5.2.1
      - descript-audio-codec==1.0.0
      - descript-audiotools==0.7.2
      - diff-match-patch==20241021
      - docstring-parser==0.17.0
      - easydict==1.13
      - editdistance==0.8.1
      - einops==0.8.1
      - executing==2.2.1
      - fairseq==0.12.2
      - fastapi==0.121.2
      - ffmpy==1.0.0
      - fire==0.7.1
      - flatbuffers==25.9.23
      - flatten-dict==0.4.2
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - funasr==1.2.7
      - future==1.0.0
      - gdown==5.2.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface==0.0.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.0.7
      - idna==3.11
      - importlib-resources==6.5.2
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jaconv==0.4.0
      - jamo==0.4.1
      - jedi==0.19.2
      - jieba==0.42.1
      - jiwer==4.0.0
      - jmespath==0.10.0
      - joblib==1.5.2
      - julius==0.2.7
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - modelscope==1.31.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - networkx==3.5
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.0.6
      - onnxruntime==1.23.2
      - orjson==3.11.4
      - oss2==2.19.1
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pesq==0.0.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - pip==25.1
      - platformdirs==4.5.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==3.19.6
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyloudnorm==0.1.1
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.6
      - pytorch-wpe==0.0.1
      - pytz==2025.2
      - randomname==0.2.1
      - rapidfuzz==3.14.3
      - rarfile==4.2
      - regex==2025.11.3
      - requests==2.32.5
      - resampy==0.4.3
      - rich==14.2.0
      - ruff==0.14.5
      - sacrebleu==2.5.1
      - safehttpx==0.1.7
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - sox==1.5.0
      - soxr==1.0.0
      - stack-data==0.6.3
      - starlette==0.49.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6
      - termcolor==3.2.0
      - termplotlib==0.3.9
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.6.0
      - torch-complex==0.4.4
      - torch-stoi==0.2.3
      - torchlibrosa==0.1.0
      - torchmetrics==1.8.2
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==3.2.0
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - webvtt-py==0.5.1
      - werkzeug==3.1.3
      - wget==3.2
      - yarl==1.22.0
prefix: /mnt/nas1/anaconda3/envs/codec
